name = "fpl-live-draft"
main = "worker.js"
compatibility_date = "2024-10-01"

[assets]
directory = "."
binding = "ASSETS"
html_handling = "auto"
not_found_handling = "none"

[vars]
NODE_ENV = "production"


